const fs=require('node:fs');const path=require('node:path');const {parseHTML}=require('linkedom');
const root=path.resolve(__dirname,'..');const catalog=JSON.parse(fs.readFileSync(path.join(root,'catalog.json'),'utf8'));
const modules={'PlanCuenta':'plan-cuenta','Voucher':'voucher','Compras':'compras','Ventas':'ventas','Honorarios':'honorarios','Bancos':'banco','Remuneraciones':'remuneraciones','ActivosFijos':'activos-fijos','Ifrs':'ifrs','Parametros':'parametros','Reportes':'reportes','Tesoreria':'tesoreria','Tributario':'tributario','RCV':'rcv','Analitica':'analitica'};
const routes=Object.fromEntries(Object.entries(modules).map(([k,v])=>['js_icargarModulo'+k,v+'.html']));routes.js_icargarCotabilidadExpress='cont-express.html';routes.js_cargarIntefazTrabajoEmpresa='panel.html';
const actions={'js_cAVOU':'voucher-crear','js_cAVEN':'ventas-crear','js_cACOM':'compras-crear','js_cAHON':'honorarios-crear','js_cIMCOM':'compras-importacion-detallada','js_cIMCOMSIM':'compras-importacion-directa','js_cIMVEN':'ventas-importacion-detallada','js_cIMVENSIMP':'ventas-importacion-directa','js_cIMHON':'honorarios-importacion','js_cVBOL':'ventas-boletas','js_cAEP':'remuneraciones-empleado-crear','js_impFicEmp':'remuneraciones-empleados-importar','js_cargarGestionAdministracion':'usuarios','js_cargarGestionEmpresa':'empresas','js_cargarDatosContador':'perfil','js_cargarConceptosGlobales':'globales','js_cargarAuditoria':'control','js_CmbrEmprSlcnd':'inicio-cuenta'};
const normalize=s=>s.replace(/[^\p{L}\p{N}\s|()./-]/gu,'').replace(/\s+/g,' ').trim();
const shared={'Agregar Cuenta':'plan-cuenta-agregar','Agregar Sub-Tipo':'plan-cuenta-subtipo','Crear Usuario':'usuarios-crear','Descuadrados':'voucher-descuadrados','Comprobantes':'voucher-comprobantes','Inf. Vacaciones':'remuneraciones-vacaciones','Inf. Licencias Médicas':'remuneraciones-licencias','Datos Generales':'perfil','Facturas Emitidas':'perfil-facturas','Cambiar tu clave':'perfil-clave'};
fs.writeFileSync(path.join(root,'routes.json'),JSON.stringify({modules:routes,actions},null,2));
for(const item of catalog){const file=path.join(root,item.file);const {document}=parseHTML(fs.readFileSync(file,'utf8'));
 const offlineStyle=document.querySelector('link[href="../assets/offline.css"]');if(offlineStyle)document.head.append(offlineStyle);
 document.querySelectorAll('.ui-dialog').forEach(e=>{e.removeAttribute('aria-hidden');e.classList.remove('fixed-dialog');e.setAttribute('style',e.getAttribute('style')+';position:relative!important;top:auto!important;left:auto!important;transform:none!important;margin:28px auto!important;');});
 document.querySelectorAll('a').forEach(a=>{let dest;const label=normalize(a.textContent);const action=a.getAttribute('data-local-action');if(actions[action])dest=actions[action]+'.html';if(shared[label])dest=shared[label]+'.html';
 const family=item.name.split(' · ')[0];const match=catalog.find(c=>c.name.startsWith(family+' · ')&&normalize(c.name.split(' · ').slice(1).join(' · '))===label);if(match)dest=path.basename(match.file);
 if(label==='Crear/Importar Cartola')dest='banco-cartola.html';if(label==='Crear Movimiento Tesoreria')dest='tesoreria-crear.html';if(label==='Credenciales'&&item.file.startsWith('views/rcv'))dest='rcv-credenciales.html';
 if(item.file.startsWith('views/compras')){const labels={'Compra':'compras-crear','Importación Masiva Detallada':'compras-importacion-detallada','Importación Masiva Directa':'compras-importacion-directa'};if(labels[label])dest=labels[label]+'.html';}
 if(label==='Importar'&&item.file.startsWith('views/parametros')){const panel=a.closest('[role=tabpanel]');const name=normalize(panel?.getAttribute('aria-labelledby')?document.getElementById(panel.getAttribute('aria-labelledby'))?.textContent||'':'');const type=['Proveedores','Clientes','Honorarios'].find(t=>name===t||panel?.id?.toLowerCase().includes(t.toLowerCase()));if(type)dest='parametros-'+type.toLowerCase()+'-importar.html';else if(item.file.includes('proveedores'))dest='parametros-proveedores-importar.html';else if(item.file.includes('clientes'))dest='parametros-clientes-importar.html';else if(item.file.includes('honorarios'))dest='parametros-honorarios-importar.html';}
 if(item.file.includes('remuneraciones')&&label==='Agregar')dest=item.file.includes('laborales-lote')?'remuneraciones-laborales-lote-agregar.html':'remuneraciones-globales-agregar.html';
 if(item.file.includes('empleado-')){const employee={'Personales':'remuneraciones-empleado-crear','Laborales':'empleado-laborales','Prevision y Salud':'empleado-prevision','APV (I-C)':'empleado-apv','Haberes':'empleado-haberes','Descuentos':'empleado-descuentos','Contratos y Finiquitos':'empleado-contratos'};if(employee[label])dest=employee[label]+'.html';}if(item.file.includes('remuneraciones')&&label==='Liquidación')dest='remuneraciones.html';
 for(const [cls,target] of Object.entries(routes))if(a.classList.contains(cls))dest=target;if(dest)a.setAttribute('href',dest);
 const tab=a.closest('[role=tab]');if(!dest&&tab?.getAttribute('aria-controls')&&document.getElementById(tab.getAttribute('aria-controls')))a.setAttribute('data-offline-panel',tab.getAttribute('aria-controls'));
 });
 document.querySelectorAll('style').forEach(e=>{e.textContent=e.textContent.replace(/@import[^;]+;/gi,'').replace(/url\((?!["']?#)[^)]+\)/gi,'none');});
 document.querySelectorAll('table.dataTable tbody tr,table[role=grid] tbody tr').forEach(r=>r.removeAttribute('id'));
 const cleanText=e=>{for(const n of [...e.childNodes]){if(n.nodeType===3){n.textContent=n.textContent.replace(/[A-ZÁÉÍÓÚÑ][A-ZÁÉÍÓÚÑ ]{10,}EMPRESA INDIVIDUAL DE RESPONSABILIDAD LIMITADA/gi,'EMPRESA DEMO SPA');if(/^(?:-?\d+[.,]?\d*%?|\d+M)$/.test(n.textContent.trim())&&!e.closest('option,table,script,style')&&!/^20\d\d$/.test(n.textContent.trim()))n.textContent='100';}else cleanText(n);}};cleanText(document.body);
 document.querySelectorAll('.highcharts-root').forEach(svg=>{svg.querySelectorAll('[aria-label="Serie ficticia de ejemplo"]').forEach(e=>e.remove());const g=document.createElementNS('http://www.w3.org/2000/svg','g');g.setAttribute('aria-label','Serie ficticia de ejemplo');for(let i=0;i<8;i++){const r=document.createElementNS('http://www.w3.org/2000/svg','rect');const h=[45,70,90,55,110,80,120,100][i];r.setAttribute('x',String(95+i*44));r.setAttribute('y',String(235-h));r.setAttribute('width','24');r.setAttribute('height',String(h));r.setAttribute('fill','#86b6ef');g.append(r);}svg.append(g);});
 document.querySelectorAll('a[title],*[data-id-emp],*[data-nom-emp]').forEach(e=>{e.removeAttribute('title');e.removeAttribute('data-id-emp');e.removeAttribute('data-nom-emp');});
 fs.writeFileSync(file,'<!doctype html>\n'+document.documentElement.outerHTML);
}
console.log('Finalizadas '+catalog.length+' vistas.');

