const fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'..'),map=JSON.parse(fs.readFileSync(path.join(root,'assets-map.json'),'utf8')),missing=new Set();
for(const [url,local] of Object.entries(map)){
 if(!local.endsWith('.css'))continue;
 const filename=path.join(root,local.replace('../','')),original=path.join(root,'reference/styles',path.basename(filename));let css=fs.readFileSync(fs.existsSync(original)?original:filename,'utf8');
 css=css.replace(/@import\s+(?:url\()?['"]?https?:[^;]+;/gi,'');
 css=css.replace(/url\(\s*(['"]?)(.*?)\1\s*\)/gi,(match,q,value)=>{
  if(value.startsWith('#')||value.startsWith('data:'))return match;
  let absolute;try{absolute=new URL(value,url).href;}catch{return 'none';}
  const clean=absolute.split('?')[0];const found=map[absolute]||Object.entries(map).find(([k])=>k.split('?')[0]===clean||path.basename(new URL(k).pathname)===path.basename(new URL(absolute).pathname))?.[1];
  if(found)return 'url("'+path.basename(found)+'")';missing.add(absolute);return 'none';
 });fs.writeFileSync(filename,css);
}
const catalog=JSON.parse(fs.readFileSync(path.join(root,'catalog.json'),'utf8')),notes=JSON.parse(fs.readFileSync(path.join(root,'coverage-notes.json'),'utf8'));
const modules=['Plan de Cuenta','Voucher','Compras','Ventas','Honorarios','Banco','Remuneraciones','Activos Fijos','IFRS','Parámetros','Reportes','Tesoreria','Tributario','Cont. Express','RCV','Analítica'];
const status={status:'captured-with-limitations',sourceDate:'2026-10-02',surveyedModules:modules,unlicensedModules:['Activos Fijos','Tributario','Cont. Express'],views:catalog.length};fs.writeFileSync(path.join(root,'capture-status.json'),JSON.stringify(status,null,2));
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const groups=new Map();for(const c of catalog){let family=c.name.split(' · ')[0];if(family==='Empleado')family='Remuneraciones';if(family==='Globales'||family==='Cuenta'||['Inicio de la cuenta','Empresas','Panel principal'].includes(family))family='Cuenta y panel';if(!groups.has(family))groups.set(family,[]);groups.get(family).push(c);}
fs.writeFileSync(path.join(root,'index.html'),`<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><meta http-equiv="Content-Security-Policy" content="default-src 'self'; connect-src 'none'; style-src 'self' 'unsafe-inline'; form-action 'none'"><title>iContador · Copia local</title><style>body{font:16px system-ui;margin:40px auto;max-width:1080px;padding:0 24px;color:#24354a;background:#f5f7fa}h1{color:#173759}a{color:#1467b3}li{margin:12px 0}section{background:white;padding:16px 24px;margin:16px 0;border:1px solid #d9e0e8;border-radius:8px}.notice{padding:20px;background:#fff3d4;border-radius:8px}small{color:#526579}</style></head><body><h1>iContador · Copia local</h1><p>${catalog.length} vistas editables · ${modules.length} módulos revisados · Datos ficticios</p><p><a href="views/panel.html">Abrir panel principal</a></p><div class="notice">Referencia visual sin backend. Activos Fijos, Tributario y Cont. Express muestran el aviso de servicio no contratado. Las acciones que requieren guardar registros y los informes generados no se ejecutaron.</div>${[...groups].map(([name,items])=>`<section><h2>${escape(name)}</h2><ul>${items.map(c=>`<li><a href="${escape(c.file)}">${escape(c.name)}</a></li>`).join('')}</ul></section>`).join('')}<p><a href="inventory.json">Inventario y limitaciones</a> · <a href="README.md">Instrucciones</a></p><small>Captura: 2 de octubre de 2026. No incluye PHP, base de datos ni credenciales.</small></body></html>`);
const inventory={...status,views:catalog,javascript:fs.readdirSync(path.join(root,'reference/javascript')),assets:Object.keys(map).length,missingCssResources:[...missing],unavailableResources:['favicon.ico','icon-error-modal.png','icon-envio-exito.png','icon-altoparlante.png'].map(name=>({name,reason:'HTTP 404 en el sitio original'})),exclusions:notes,limitations:['No incluye backend PHP ni base de datos','Scripts originales archivados y nunca ejecutados; no se sirven por HTTP','Se sustituyen tablas, datos personales y series de gráficos por ejemplos ficticios','Formularios estáticos: guardar, eliminar, enviar, pagar, sincronizar y generar informes están desactivados','Recursos CSS no observados o no recuperables se omiten','Listas desplegables dinámicas, paginación y ayudas que dependen del servidor se simplifican']};fs.writeFileSync(path.join(root,'inventory.json'),JSON.stringify(inventory,null,2));console.log(JSON.stringify({views:catalog.length,assets:inventory.assets,missingCssResources:missing.size}));
