const fs=require('node:fs');const path=require('node:path');const assert=require('node:assert/strict');const {parseHTML}=require('linkedom');const {sanitize}=require('./sanitize.js');
const root=path.resolve(__dirname,'..');const catalog=JSON.parse(fs.readFileSync(path.join(root,'catalog.json'),'utf8'));assert(catalog.length>=100,'Faltan vistas en el catálogo');let references=0;
// Vistas conectadas a la API PHP local (assets/contabilidad.js): solo ellas pueden conectarse a su propio origen.
const contabilidad=new Set(['views/voucher.html','views/voucher-crear.html','views/reportes-libro-diario.html','views/reportes-libro-mayor.html','views/reportes-libro-balance.html','views/reportes-resultados.html','views/reportes-libro-compras.html','views/reportes-libro-ventas.html','views/reportes-libro-honorarios.html']);
for(const item of catalog){const full=path.join(root,item.file);const html=fs.readFileSync(full,'utf8');const {document}=parseHTML(html);
 assert(!/<!--[\s\S]*?-->/.test(html),'Comentarios originales pendientes');assert(!/\bon\w+\s*=/i.test(html),'Handler inline');
 assert(!html.includes('[Truncated]'),'Captura truncada '+item.file);assert(!/\\b\\d{8,9}-[0-9kK]\\b/.test(html),'Identificador personal sin anonimizar '+item.file);
 for(const e of document.querySelectorAll('input,textarea'))assert(!e.getAttribute('value')&&!e.textContent.trim(),'Campo sin anonimizar '+item.file);
 for(const e of document.querySelectorAll('style,[style]'))assert(!/url\(\s*['"]?(?:https?:|\/\/)/i.test(e.textContent||e.getAttribute('style')||''),'URL externa en CSS inline');
const csp=document.querySelector('meta[http-equiv="Content-Security-Policy"]').content;assert(csp.includes(contabilidad.has(item.file)||item.file==='views/rcv.html'||item.file==='views/honorarios.html'||item.file==='views/remuneraciones-calculadora.html'||item.file==='views/inicio-cuenta.html'||item.file==='views/plan-cuenta.html'||item.file==='views/empresas.html'?"connect-src 'self'":"connect-src 'none'"),'CSP inesperada '+item.file);
 for(const e of document.querySelectorAll('[src],[href]')){const u=e.getAttribute('src')||e.getAttribute('href');if(!u||u==='#'||u.startsWith('data:'))continue;assert(!/^(?:https?:|javascript:|\/\/)/i.test(u),'Referencia externa '+u);const p=path.resolve(path.dirname(full),u.split('#')[0]);assert(fs.existsSync(p),'Falta recurso '+u);references++;}
 for(const script of document.querySelectorAll('script')){const src=script.getAttribute('src');assert(['../assets/offline.js','../assets/rcv-import.js','../assets/footer-badge.js'].includes(src)||(item.file==='views/remuneraciones-calculadora.html'&&src==='../assets/liquidacion.js')||(contabilidad.has(item.file)&&src==='../assets/contabilidad.js')||(item.file==='views/plan-cuenta.html'&&src==='../assets/plan-cuenta.js')||(item.file==='views/empresas.html'&&src==='../assets/empresas.js')||(item.file==='views/honorarios.html'&&src==='../assets/honorarios-import.js'),'Script original ejecutable');}
 assert(!document.querySelector('input[type=hidden]'));assert(!document.querySelector('iframe'));assert(!document.querySelector('[data-id-emp]'));
}
for(const file of fs.readdirSync(path.join(root,'assets')).filter(f=>f.endsWith('.css'))){const css=fs.readFileSync(path.join(root,'assets',file),'utf8');for(const m of css.matchAll(/url\(\s*['"]?([^)'"\s]+)['"]?\s*\)/g)){if(m[1].startsWith('#')||m[1].startsWith('data:'))continue;assert(!/https?:|^\/\//i.test(m[1]));assert(fs.existsSync(path.join(root,'assets',m[1])),'Falta recurso CSS '+m[1]);}}
const fixture='<html><head><script>document.cookie="SECRET"</script></head><body><!-- SECRET --><a onclick="fetch(1)" href="https://external.invalid">Abrir</a><input type="hidden" value="SECRET"><input type="password" value="SECRET"><table class="dataTable"><tbody><tr><td>PERSONA PRIVADA</td></tr></tbody></table><iframe src="https://external.invalid"></iframe></body></html>';
const clean=sanitize(fixture,{});assert(!clean.includes('SECRET'));assert(!clean.includes('PERSONA PRIVADA'));assert(!clean.includes('external.invalid'));
const report={status:'passed',views:catalog.length,localReferences:references,checks:['referencias locales existentes','CSP sin conexiones externas (solo vistas contables hacia la API local)','sin scripts originales activos','sin iframe ni inputs ocultos','fixture de privacidad y sanitización']};fs.writeFileSync(path.join(root,'verification.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));

